osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
- npm install

script:
- npm run dist-mac
- git add dist/

deploy:
  provider: heroku
  buildpack: php
  strategy: git
  api_key:
    secure: jAjVqqnNS5tl2djYzm4bgwnJRPIm74yCslV6DTio+RGQwu/ZLu9V5OblEcBJHWd6J/d/PbTkjJDWyrmzlA2GvkIfcHsT5mFkWrXyYUrGAEOAtMf4SodtdXdspZyLvugnueRemTViloQ31utNrQ6oj5rHln6x2oT+/Qx/arjmmSPSZ2Ou4J1orkYjU9W+0p7tHhfsXwbhYMFrRV8+wdG/eObbJ1z6iqqkIYBYPS3CpztScscvpt5HF4lpQ47b/MAOCCIdf0FKZA8s2BUehwmsLZOxICzUqA8WxPPiz2FaWOi4RYEFLAToTtsMD+FV5psm6SiIDCEwzLGIF/gcOMbprYz1y8GFNE3Bm9nNeYMrU7MKA77UhcS/X66fbONsAHv9LRuNwnwK4sSyb4XXNpFrTzYiWUsG0TUhv2G/ayQb2LiuGO51fU8ap0k5+HMDal+y3n4Hf0o8BY/tbcuaLAoB5dEHVSlI5MIlgqYmsSq67wchd4PZr8T6rQaTDu6gtKK84q/vWb9+2lfHAEcmhFi4nkPzw3LnDKoFVJaU6wfummd+t0YE+Alj0KvubGM8uu7q/L5ALx4r+KHlllfd8uFY8pSpWfaGFmZHu63a6RNch7GNgbzIQnE7hXGhjYLy+0qEhlM7WwnRt1V11oOXYstbNuRCVysTtChkZLBl+HEOPfE=
  app: whatsupdev
  on:
    repo: LckySndays/LanyangWhatsUp
    
  provider: releases
  api_key:
    secure: Ci69wQ0VWFdvmDWRQigwPabvM4j+Bujs8Gjyffz1akIbulhB4As0HxSy9zST4y60xb2ZlZu0QQJh3dLUawcTSYyT+znhOZ5V2zCE+5J0TjSyoylcgl2eoKdot8aV7TpXsbQzB5ZgWN89WD7rsz1e1gHiWWQautSIDhMDSXYQonqlBcgSVxSLuVSVXJt2t2ThBUrOVCfn4o9p/NpBbzAd7Z1d5cGBesjr48MPz3+OAyxsrjSH4zCKWTWWPKymR6QDBTZ/Qs609LK6DyvAxOXe6rk9LGO9TaRX26lzsvxdDp4NCUhAt+AIrzHKX3aX3b6U34RxKyE24huQCDACzxu9xq0yv0dyVJk73q40BjTxt++Qut/OEBk/ly3PhyYbsT4Go0XK7/YAuzXOeoqA9N4WQZ1ws9TjtzT9E/pLpXPDGuxbxA9Dv38kfsVU1BdDeDzD9sMmQWAYTExIzW2aEh+HIf/x2y0aHYRtjJliLYuP5uD4cYmMYIVyEMJixnFmvnmxmUR0s6NGIYfRxAgh/ldwfQd2221zBcypHCBrJAkwCm+INSbUSG1lq0yOJFjIlO0UMGEMHu0mYoCp4HuNhlnhF4nMcXXbmtAw0yRBf4IQH+mDAf4jUlhl7wj16CjWIIYCnv+c00+t60+NuV8tgLz4x1P72LkWdVupEpPyI1ATdmY=
  file: dist/
  on:
    repo: LckySndays/LanyangWhatsUp
