osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
- npm install

script:
- npm run dist-mac

deploy:
  provider: releases
  api_key: dd56049f7cd0413fd347e6c0d7c406a4783f92ea
  skip_cleanup: true
  on:
    tags: true
